### ISSUE TITLE
Script running issues

### ISSUE THREAD

**Issue by CTRL-ALT-UP** [ivanus0/iProg-script-disasm#1]
**_Hello, Thanks for spending time writing these scripts._**

**_Im having a few issues with it. It seems to work perfectly on a few scripts but having issues with most._**

**_here is an example of what is happening_**

ctrl-alt-up@EliteMini:~/iPROG-FILES/iProg-script-disasm-master$ python3 iProgDecompiler.py fulltest.ipr
Processing: fulltest.ipr
Traceback (most recent call last):
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/iProgDecompiler.py", line 42, in <module>
    decompile(filename)
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/iProgDecompiler.py", line 34, in decompile
    decompile_ipr(source_filename)
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/iProgDecompiler.py", line 9, in decompile_ipr
    ipr.decompile()
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/ipr.py", line 1252, in decompile
    self.decompile_window()
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/ipr.py", line 915, in decompile_window
    caption = self.stream.read_str(b'\r')
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/stream.py", line 111, in read_str
    return result.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: invalid continuation byte

**After it displayed the above message i converted the russian language to english and it seemed to reduce some of the issues**

ctrl-alt-up@EliteMini:~/iPROG-FILES/iProg-script-disasm-master$ python3 iProgDecompiler.py fulltest.ipr
Traceback (most recent call last):
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/iProgDecompiler.py", line 3, in <module>
    from ipr import IPR
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/ipr.py", line 3, in <module>
    from decode import decode_devicebytecode
  File "/home/ctrl-alt-up/iPROG-FILES/iProg-script-disasm-master/decode.py", line 33
    if (sn_encoded >> 0x10 ^ sn_encoded) & 0xFFFF == 0x1234:
                                                            ^
IndentationError: unindent does not match any outer indentation level

**Any ideas how to get it working?**

**Comment by ivanus0** [comment]
Fix it  5e8996c
