### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by postarc** [ivanus0/iProg-script-disasm#2]
I'm trying to compile a file and I get this error:
Traceback (most recent call last):
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\iProgDecompiler.py", line 48, in <module>
    decompile(filename)
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\iProgDecompiler.py", line 34, in decompile
    decompile_ipr(source_filename)
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\iProgDecompiler.py", line 9, in decompile_ipr
    ipr.decompile()
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\ipr.py", line 1253, in decompile
    self.decompile_script()
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\ipr.py", line 1234, in decompile_script
    code.extend(self.device_listing.disassemble(DisassemblerIPR))
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\listing.py", line 243, in disassemble
    self.dis.postprocess()
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\ipr.py", line 474, in postprocess
    self.postprocess_proc(f)
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\ipr.py", line 531, in postprocess_proc
    line.set_comment(f'if ({line.arg_str(0)} {ncond} {line2.arg_str(1)}) {{')
  File "D:\Coding\Python\Projects\iProg-script-disasm-v0\listing.py", line 66, in arg_str
    return self.listing.dis.arg_str(self.args[n])
IndexError: list index out of range

Process finished with exit code 1
[UAZ_AP_78F0836_ODO.zip](https://github.com/ivanus0/iProg-script-disasm/files/13401200/UAZ_AP_78F0836_ODO.zip)

**Comment by postarc** [comment]
Adding a try opertor to this section of the code solves the problem, but I’m not sure that the algorithm of the program is not broken:
    def arg_str(self, n):
        try:
            return self.listing.dis.arg_str(self.args[n])
        except:
            return 0

**Comment by antonpasm** [comment]
corrected db8f128

**Comment by ivanus0** [comment]
Corrected db8f128
