### ISSUE TITLE
BMW FRM decompile

### ISSUE THREAD

**Issue by foskr** [ivanus0/iProg-script-disasm#4]
Hello. Could you add this script decompiled to the folder?
[FRM_9s12xeq384_DFlash_EEE_ed2.zip](https://github.com/ivanus0/iProg-script-disasm/files/14019843/FRM_9s12xeq384_DFlash_EEE_ed2.zip)

**Comment by ivanus0** [comment]
No problem
[FRM_9s12xeq384_DFlash_EEE_ed2.blr](../blob/master/examples/decompiled/FRM_9s12xeq384_DFlash_EEE_ed2.blr)

**Comment by foskr** [comment]
Огромное Вам спасибо

**Comment by foskr** [comment]
C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master>iProgDecompiler.py FRM_9s12xeq384_DFlash_EEE_ed2.ipr
Traceback (most recent call last):
  File "C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master\iProgDecompiler.py", line 3, in <module>
    from ipr import IPR
  File "C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master\ipr.py", line 4, in <module>
    from ipr_decomp import decompile, decompile_post
  File "C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master\ipr_decomp.py", line 1200
    listing.glob.append(f'string {', '.join(f'str_{i}' for i in range(max(s) + 1))};')
                                   ^
SyntaxError: f-string: expecting '}'
