### ISSUE TITLE
BMW FRM

### ISSUE THREAD

**Issue by foskr** [ivanus0/iProg-script-disasm#5]
C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master>iProgDecompiler.py FRM_9s12xeq384_DFlash_EEE_ed2.ipr
Traceback (most recent call last):
  File "C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master\iProgDecompiler.py", line 3, in <module>
    from ipr import IPR
  File "C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master\ipr.py", line 4, in <module>
    from ipr_decomp import decompile, decompile_post
  File "C:\iProg+V86\Scripts\В работе\000\iProg-script-disasm-master\ipr_decomp.py", line 1200
    listing.glob.append(f'string {', '.join(f'str_{i}' for i in range(max(s) + 1))};')
                                   ^
SyntaxError: f-string: expecting '}'

**Comment by ivanus0** [comment]
Fixed 49043f2

**Comment by foskr** [comment]
Теперь работает

**Comment by foskr** [comment]
Огромное Вам спасибо
